title: wusong
description: wusongfayuan

url: http://www.wusong.me/

theme: donob

per_page: 7

# menu
menu:
  Archives: /archives/
  About: /about/

default_category: blog

user: fydy
repository: fydy.github.io

plugins:
  - acyort-rss
  - acyort-archives
  - acyort-paginator

public_dir: public

authors:
  - fydy

timezone: Asia/Shanghai

language:

line_numbers:

order:

token: 8#aff904696956cce9371882f55e448b9b3a2793b

cache: true

rss: true

archives:
  per_page: 30
