# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:latest

    working_directory: ~/acyort

    branches:
      only:
        - gh-pages

    steps:
      - checkout
      - run: npm i acyort@2.3 -g
      - run: acyort init
      - run: cp config.bak.yml config.yml
      - run: npm i
      - run: git clone https://github.com/acyortjs/theme-donob.git themes/donob
      - run: acyort build
      - run: git checkout .
      - run: git checkout master
      - run: git reset --hard origin/master
      - run: cp -R public/* .
      - run: rm config.bak.yml
      - run: rm -R scripts themes public
      - run: git add .
      - run: git config user.name "fydy"
      - run: git config user.email "barberw@mail.lcc.edu"
      - run: git commit -m "Updated by circleci - `date`"
      - run: git push -q https://${gh_token}@github.com/fydy/fydy.github.io.git master:master
